@startuml
actor HR as "HR Advisor"

actor employee as "Employee"

rectangle database

rectangle "HR System" {


    usecase UC5 as "Employee Details File"

    usecase UC4 as "New employee details"

    usecase UCa as "Delete employee files from database"

    HR - UC5
        UC5 ..> UCa : include
        UC4 - employee
        UC5 - UC4
        UCa - database
@enduml