@startuml


actor User as "Member"

rectangle Database

rectangle "Population System" {


    usecase UC5 as "Continent/Region/Country"

    usecase UC4 as "Overall Population"

    usecase UCa as "Population living in cities in %"

    usecase UCb as "population not living in cities in %"

    User - UC5
    UC4 ..> UCa : include
    UC4 ..> UCb : include
    UC4 - Database
    UC5 ..> UC4
@enduml