@startuml
:Main Admin: as Admin
(Use the application) as (Use)

actor HR as "HR Advisor"

rectangle Database

rectangle "HR Salary System(HR Salary file)" {


    usecase UC5 as "Creating HR file"

    usecase UC4 as "Get salaries
    from HR employees"

    usecase UCa as "Print salaries"

    HR - UC5
    UC4 ..> UCa : include
    UC4 - Database
    UC5 - UC4
@enduml